### ISSUE TITLE
Interpreting output of morton3D_64_encode

### ISSUE THREAD

**Issue by daviddoria** [Forceflow/libmorton#11]
Here is a demo that is just a loop over a 3x3 cube. I guess I expected the values 0-26 to come back in some shuffled version, but instead I got:

0 1 8 2 3 10 16 17 24 4 5 12 6 7 14 20 21 28 32 33 40 34 35 42 48 49 56
```

#include <iostream>

#include "include/morton.h"

int main()
{
    for(unsigned int z = 0; z < 3; ++z)
    {
        for(unsigned int y = 0; y < 3; ++y)
        {
            for(unsigned int x = 0; x < 3; ++x)
            {
                int index = morton3D_64_encode(x,y,z);
                std::cout << "index: " << index << std::endl;
            }
        }
    }

  return 0;
}
```

Can you explain how to interpret these indices?

Thanks!

David

**Comment by Forceflow** [comment]
Try interpreting them using this:

``
	for (unsigned int z = 0; z < 3; ++z)
	{
		for (unsigned int y = 0; y < 3; ++y)
		{
			for (unsigned int x = 0; x < 3; ++x)
			{
				uint_fast64_t index = morton3D_64_encode(x, y, z);
				std::bitset<64> ibits(index);
				std::cout << "index: " << ibits << std::endl;
			}
		}
	}
``

**Comment by daviddoria** [comment]
Ok, thanks. What I'm actually trying to use this for is compression of a binary 3D matrix. I've heard that making a 1D string of bits of the values in my grid in "Morton order" will compress much better than the 1D string from raster scan order. So the above code is then actually kind of the opposite of what I want. If I try this:

`    for(unsigned int i = 0; i < 27; ++i)
    {
        uint_fast32_t x,y,z;
        morton3D_64_decode(i, x, y, z);

        std::cout << "(" << x << "," << y << "," << z << ")" << std::endl;
    }
`
which is an attempt to get the "Morton ordering" of my 3x3x3 example grid, I get values outside the grid extents (as you've already explained, "Morton index 9" requires a X coordinate of 3, which I never have). Is there a way to get this besides just continuing to increment 'i' until I've made sure that all of my coordinates have been assigned their Morton order value?

**Comment by daviddoria** [comment]
This does what I was looking for:

```
#include <bitset>
#include <iostream>
#include <vector>
#include <set>

#include "include/morton.h"

class CellCoordinate
{
public:
    CellCoordinate(){}
    CellCoordinate(int x, int y, int z) : mX(x), mY(y), mZ(z) { }

    int mX,mY,mZ;
};

int main()
{
    typedef int MortonIndex;
    typedef std::pair<CellCoordinate, MortonIndex> MortonPair;

    auto comp = [](const MortonPair& x, const MortonPair& y){ return x.second < y.second; };

    typedef std::set<MortonPair, decltype(comp) > MortonSet;
    MortonSet mortonOrdering(comp);

    for(unsigned int z = 0; z < 3; ++z)
    {
        for(unsigned int y = 0; y < 3; ++y)
        {
            for(unsigned int x = 0; x < 3; ++x)
            {
                uint_fast64_t index = morton3D_64_encode(x, y, z);
                std::pair<CellCoordinate, MortonIndex> item;
                item.first = CellCoordinate(x,y,z);
                item.second = index;
                mortonOrdering.insert(item);
            }
        }
    }

    for(MortonSet::const_iterator iterator = mortonOrdering.begin(); iterator != mortonOrdering.end(); ++iterator)
    {
        std::pair<CellCoordinate, MortonIndex> item = *iterator;
        CellCoordinate mortonIndex = item.first;
        std::cout << item.second << ": (" << mortonIndex.mX << "," << mortonIndex.mY << "," << mortonIndex.mZ << ")" << std::endl;
    }

    return 0;
}
```

The question now is just if it is actually helpful to encode a grid in this order!

**Comment by Forceflow** [comment]
That's for you to find out :)

Keep in mind: you will only traverse the full index range if your n x n x n box of coordinates has n = a power of 2.

3 is not a power of 2, that's why you don't get your morton indices over the full range.

See this image on Wikipedia for a visualization: https://en.wikipedia.org/wiki/Z-order_curve#/media/File:Lebesgue-3d-step2.png
