### ISSUE TITLE
MIT/BSD/ZLIB/something dual license?

### ISSUE THREAD

**Issue by renindustries** [Forceflow/libmorton#13]
Hey, I was very interested in using this in a small open source 2D/3D engine to speed up collision detection, but I unfortunately am targeting a BSD style license. Is there any way we could get a dual license version of this?

Thank you!

**Comment by Forceflow** [comment]
Hey, I'm cool with this - just make sure to link to the original project and reference me :)

The things libmorton does are not rocket science, so have fun with it.

**Comment by Forceflow** [comment]
Switched to MIT in commit #7ee35898a3c1a7bfc7a3c3b178870b0a397006f0

**Comment by Alicemargatroid** [comment]
@Forceflow Will do, thank you kindly!
