### ISSUE TITLE
3D Morton for-loop encoding is broken

### ISSUE THREAD

**Issue by EBatut-ALG** [Forceflow/libmorton#14]
Hi

In morton3D.h, lines 120 and 141, the shift variable should be initialized to 3*i, not 2*i, otherwise some bits are overwriting bits from the previous iterations.

I made the same comment on the original blogpost: http://www.forceflow.be/2013/10/07/morton-encodingdecoding-through-bit-interleaving-implementations/#comment-7508

Thanks for the lib !
Eric

**Comment by EBatut-ALG** [comment]
And probably lines 244 and 262 should be checked as well ?

**Comment by Forceflow** [comment]
Fixed lines 120 x 141 - I'll check the other lines as well.

The for-loop methods are there for legacy reasons only, I don't think any sane person would use them to compute morton codes _fast_. :) But still, needs to be correct!

**Comment by Forceflow** [comment]
I've looked at this issue again,  and I think it needs to be 2i.

You see,  you use one bit to select a certain bit in your coordinate (x, y or z)  at position i. 

Let's say we select the bit at position 2. (so the third bit from the right).  If we shift that back to 0, we do >> i,  so >> 2. Then we need to get it at the correct position in the final Morton code.  Let's say it's the X coordinate,  so we have to  shift it to position 6 (which is the seventh bit form the right in the Morton code).  

The total shift you do (2 to the right,  6 to the left)  is 2i.

I can be wrong,  I'm on a train,  and debugging on my phone is hard. What do you think? 

Still something wrong with the early termination version,  but I reverted the change for the regular for loop for now.

**Comment by EBatut-ALG** [comment]
In the first iteration (i=0), you compute the correct bits (the first one) from x, y and z, then with shift=2*i, you shift them back to positions 0, 1, 2 to form the final answer.
In the second iteration (i=1), you compute the correct bits (the second one) from x, y, and z, then with shift=2*i, you shift them back to positions 2, 3, 4 to form the final answer.

With shift=2*i, the Z bit which was written at position 2 in the first iteration is overwritten by the X bit from iteration 1, which does not happen with shift=3*i.

**Comment by Forceflow** [comment]
You forget that those bits you're talking about are already in position 1! So I'm shifting them to 3,4,5 :)

**Comment by EBatut-ALG** [comment]
Urgh, the bug was in my brain all along :)

Thanks for the clarification !
