### ISSUE TITLE
Cuda version

### ISSUE THREAD

**Issue by acdemiralp** [Forceflow/libmorton#22]
Dear Jeroen,

I modified this library to work with Cuda for my thesis (also made it a single file). I am attaching it in case you are interested. Keep in mind it's not well tested yet (I'm still in the process of designing my linear octree).

Best Regards,
Ali

[morton.zip](https://github.com/Forceflow/libmorton/files/478265/morton.zip)

**Comment by Forceflow** [comment]
Nice - make sure to make a reference to this library in your Thesis text! Good luck!

**Comment by dtfboys** [comment]
Dear Jeroen,
I want to know if cuda version morton can work? If it can work, how can i use it?
thank you!
Best Regards,
rui
