### ISSUE TITLE
A _mm512_bitshuffle_epi64_mask method (vpshufbitqmb, AVX512_BITALG)

### ISSUE THREAD

**Issue by Wunkolo** [Forceflow/libmorton#35]
In anticipation of [Icelake bringing AVX512 to consumer hardware](https://en.wikipedia.org/wiki/AVX-512#CPUs_with_AVX-512), I've come up with an alternative to the `pdep` method for encoding a 32-bit 2D coordinate into a 64-bit morton code which utilizes the [`vpshufbitqmb` instruction](https://en.wikipedia.org/wiki/AVX-512#New_instructions_in_AVX-512_VPOPCNTDQ_and_AVX-512_BITALG) of the BITALG subset of AVX512.
`vpshufbitqmb` allows building a new value bit by bit by indexing into a 64-bit lane(into an AVX512 `k`-register mask).

It relies on interpreting two 32-bit X and Y coordinates as a continuous 64-bit value though. It can support much higher dimensions provided you `zip`(as in, feed in and interleave the leading bytes or so of the coordinates vector elements into each 64-bit lane before selecting bits) certain bytes of the input coordinates.

There is no throughput or latency data at the moment for this instruction or any hardware to actually test this upon but the assembly looks very promising. Especially for any bulk-processing where all the constants are loaded outside of the loop.

An illustrative example code of the two methods:
```cpp
#pragma pack(push, 1)
union Coord2D
{
	std::uint32_t u32[2]; // x, y
	std::uint64_t u64;
};
#pragma pack(pop)

std::uint64_t Morton2DEncode( const Coord2D& coord )
{
	const __m512i CoordVec = _mm512_set1_epi64(coord.u64);
	// Interleave bits from 32-bit X and Y coordinate
	const __mmask64 Interleave = _mm512_bitshuffle_epi64_mask(
		CoordVec,+
		_mm512_set_epi16(
			0x20'00 + 0x01'01 * 31, 0x20'00 + 0x01'01 * 30,
			0x20'00 + 0x01'01 * 29, 0x20'00 + 0x01'01 * 28,
			0x20'00 + 0x01'01 * 27, 0x20'00 + 0x01'01 * 26,
			0x20'00 + 0x01'01 * 25, 0x20'00 + 0x01'01 * 24,
			0x20'00 + 0x01'01 * 23, 0x20'00 + 0x01'01 * 22,
			0x20'00 + 0x01'01 * 21, 0x20'00 + 0x01'01 * 20,
			0x20'00 + 0x01'01 * 19, 0x20'00 + 0x01'01 * 18,
			0x20'00 + 0x01'01 * 17, 0x20'00 + 0x01'01 * 16,
			0x20'00 + 0x01'01 * 15, 0x20'00 + 0x01'01 * 14,
			0x20'00 + 0x01'01 * 13, 0x20'00 + 0x01'01 * 12,
			0x20'00 + 0x01'01 * 11, 0x20'00 + 0x01'01 * 10,
			0x20'00 + 0x01'01 *  9, 0x20'00 + 0x01'01 *  8,
			0x20'00 + 0x01'01 *  7, 0x20'00 + 0x01'01 *  6,
			0x20'00 + 0x01'01 *  5, 0x20'00 + 0x01'01 *  4,
			0x20'00 + 0x01'01 *  3, 0x20'00 + 0x01'01 *  2,
			0x20'00 + 0x01'01 *  1, 0x20'00 + 0x01'01 *  0
		)
	);
	return _cvtmask64_u64(Interleave);
}

std::uint64_t m2D_e_BMI(const Coord2D& coord)
{
	return _pdep_u64(static_cast<std::uint64_t>(coord.u32[0]), 0x5555555555555555)
		| _pdep_u64(static_cast<std::uint64_t>(coord.u32[1]), 0xAAAAAAAAAAAAAAAA);
}
```

The generated assembly using `gcc 9.1` with `-Ofast -march=icelake-client`:
```
Morton2DEncode(Coord2D const&):
        vpbroadcastq    zmm0, QWORD PTR [rdi]
        vpshufbitqmb    k0, zmm0, ZMMWORD PTR .LC0[rip]
        kmovq   rax, k0
        vzeroupper
        ret
m2D_e_BMI(Coord2D const&):
        mov     eax, DWORD PTR [rdi]
        movabs  rdx, 6148914691236517205
        pdep    rax, rax, rdx
        mov     edx, DWORD PTR [rdi+4]
        movabs  rcx, -6148914691236517206
        pdep    rdx, rdx, rcx
        or      rax, rdx
        ret
```

I have verified the implementation with [Intel's emulator](https://software.intel.com/en-us/articles/intel-software-development-emulator) and I'd love to update with some actual benchmarks once I get some Icelake hardware in my hands.

What do you think?

**Comment by Forceflow** [comment]
I like this! Generated assembly looks good, with some good timings this might beat BMI2 :) Make a PR as soon as you can test on actual hardware.

The way I would integrate it into libmorton is similar to how we support BMI2: a simple keyword (__AVX512__, for example) you have to define before including any of our headers, for those devs lucky enough to have a use case where they can guarantee that all hardware they compile for will have support :)

**Comment by Wunkolo** [comment]
Sounds great! Gonna try and get this on some Icelake hardware asap(whenever that is) and can make a PR sometime in anticipation of it possibly being much faster.

Also, totally not sure where LLVM-MCA is deriving this data from... but it looks like it says `vpshufbitqmb` is just 2 uOps with a latency of 11?

https://godbolt.org/z/MZH_01

**Comment by Forceflow** [comment]
Seems ... optimistic to me, but not impossible. Future will tell, I guess.

**Comment by Wunkolo** [comment]
[Getting on this again!](#40)

**Comment by Forceflow** [comment]
Beautiful! You can probably use the [BMI2 header](https://github.com/Forceflow/libmorton/blob/master/libmorton/include/morton_BMI.h) as an example, since integration would be the same way.

Big ol `#ifdef` to detect compilation for those icy lakes :)

**Comment by Forceflow** [comment]
Added in https://github.com/Forceflow/libmorton/commit/e7ed22928840916f8c50206b80f4936ea5754269 - closing this issue!
