### ISSUE TITLE
morton.h missing

### ISSUE THREAD

**Issue by weshoke** [Forceflow/libmorton#5]
From the README:

```You can use the library by including libmorton/morton.h. This will always include the most efficient way to date. The header morton_alternatives.h contains older / alternative implementations, for reference only.```

There is no libmorton/morton.h

**Comment by Forceflow** [comment]
Was part of it once, will make a new morton.h which has the fastest functions for 2D and 3D encode/decode

**Comment by Forceflow** [comment]
Fixed that with commit d999147e96b5585bc9b85a2dddefe74461f6d2a6
