### ISSUE TITLE
Install support in CMake scripts?

### ISSUE THREAD

**Issue by mablanchard** [Forceflow/libmorton#53]
The libmorton CMake scripts currently to not have installation directives. Would be nice to allow installing the headers to a system directory (possibly respecting the GNUInstallDirs CMAKE_INSTALL_INCLUDEDIR standard variable?). This would simplify integration of the library in complex software stacks where build is automated.

**Comment by mablanchard** [comment]
I could work on a patch if the project is willing to accept an enhancement.

**Comment by Forceflow** [comment]
Yep, we're open to enhancements :)
