### ISSUE TITLE
only cmake versions >=3.15 are supported

### ISSUE THREAD

**Issue by MR-Matthias** [Forceflow/libmorton#62]
Hi everyone,

I noticed with [commit b7c5874d68413fe7953befc97597cc6c08c824ab](https://github.com/Forceflow/libmorton/commit/b7c5874d68413fe7953befc97597cc6c08c824ab#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a) the stated "cmake_minimum_required(VERSION 3.8.2)" in CMakeLists.txt isn't correct anymore.

For cmake versions older than 3.15, you will get the following error:
> libmorton-0.2.6/CMakeLists.txt:18 (set_property):
> INTERFACE_LIBRARY targets may only have whitelisted properties. The property "PUBLIC_HEADER" is not allowed.

If it's fine to bump up the cmake minimum required version to 3.15, this would be the "easiest" fix.
Another possible workaround for the issue is described in this comment:
https://gitlab.kitware.com/cmake/cmake/-/issues/15234#note_338817

**Comment by Forceflow** [comment]
CMake 3.15 is now about 2 years old. I think we can go for the easy fix here.

**Comment by Forceflow** [comment]
Fixed in 2f2b98fb9408bcd3870d4f599ac1161a436125d8
