### ISSUE TITLE
include folder

### ISSUE THREAD

**Issue by jorgen** [Forceflow/libmorton#63]
It would be great if you could put the libmorton folder inside a include folder in the repository. In my project I download and unpack releases (tags) from github. I then set the includepath so that I can do
#include <libmorton/morton.h>
in my include files. However, to achieve this now I have to set the root project folder in the include path, making it possible to include all .gitattributes etc etc. It would therefor be nice if there was another directory that I could put in my includepath.

**Comment by Forceflow** [comment]
Yeah, a recent Cmake contributor changed that. 
Make a PR against dev, verify that cmake still works and I'll happily merge.

**Comment by Forceflow** [comment]
Merged, closing
