### ISSUE TITLE
Getting a Morton ordering of a 3D grid

### ISSUE THREAD

**Issue by daviddoria** [Forceflow/libmorton#7]
I have a (arbitrary size) 3D grid that I want to traverse in a Morton order instead of a raster scan order. Can I use these functions to do that? Or does my grid have to be exactly 32x32x32 or something like that?

**Comment by Forceflow** [comment]
Nope, doesn't have to be. You can just start encoding grid coordinates using morton3D_32_encode or morton3D_64_encode.
