### ISSUE TITLE
Computation of checkbits could be cleaned up

### ISSUE THREAD

**Issue by davemc0** [Forceflow/libmorton#75]
The lines that compute checkbits (the curve order or bits per dimension) currently use floating-point math, including floor(), which is not a trivial function, depending perhaps on the floating point handling, i.e. /fp:strict.

Here's an example: https://github.com/Forceflow/libmorton/blob/6d22725504388864751603424060ab1eef1ab8a4/include/libmorton/morton3D.h#L129

This code can be replaced with the following:
unsigned int checkbits = (sizeof(morton) * 8) / 3;

This uses integer division, includes no function call, and gives the same results in all cases.

The key to this working is the order of operations - doing the multiply first gives an intermediate result of 64 or 32. Dividing this by three yields 21 or 10, as desired.

**Comment by Forceflow** [comment]
Fixed in e01292d3b953e79afae80e39f059a519ba691541

The for-loop path is purely there for educational purposes (since it is the most transparent but slowest method to compute morton codes), but this is a nice improvement anyway.
